Update elastiflow_elasticsearch_opensearch_support_pack

diff --git a/support_pack/elastiflow_elasticsearch_opensearch_support_pack b/support_pack/elastiflow_elasticsearch_opensearch_support_pack
--- a/support_pack/elastiflow_elasticsearch_opensearch_support_pack
+++ b/support_pack/elastiflow_elasticsearch_opensearch_support_pack
@@ -3,20 +3,31 @@
 # version 1.8
 # author: O.J. Wolanyk, ElastiFlow
 
-
-
 # Setup
 current_time=$(date "+%Y%m%d%H%M%S")
-
 hostname=$(hostname)
 archive_name="elastiflow_support_pack_${hostname}_$current_time.tar.gz"
-
 log_file="script_execution.log"
 system_info_file="system.txt"
 temp_dir="temp_elastiflow_$current_time"
 
 # Create temporary directory
 mkdir -p $temp_dir
+
+# Function to get the last 200 lines of logs for specified services
+get_service_logs() {
+    local services=("elasticsearch.service" "kibana.service" "flowcoll.service" "snmpcoll.service")
+    
+    for service in "${services[@]}"; do
+        local log_file="journalctl_${service}"
+        echo "Fetching logs for $service..."
+        if journalctl -n 200 -u "$service" > "$temp_dir/$log_file" 2>/dev/null; then
+            echo "Successfully fetched logs for $service."
+        else
+            echo "Failed to fetch logs for $service or service does not exist. Continuing..."
+        fi
+    done
+}
 
 attempt_fetch_node_stats() {
     local retry_choice
@@ -30,26 +41,19 @@ attempt_fetch_node_stats() {
     case $fetch_choice in
         [Yy]* )
             while true; do
-                # Prompt user for inputs with defaults
                 read -p "Enter IP address [$default_ip]: " ip
                 ip=${ip:-$default_ip}
-
                 read -p "Enter port [$default_port]: " port
                 port=${port:-$default_port}
-
                 read -p "Enter username [$default_username]: " username
                 username=${username:-$default_username}
-
                 read -p "Enter password [$default_password]: " password
                 password=${password:-$default_password}
 
-                # Attempt to fetch node stats
                 response=$(curl -sk -u "$username:$password" "https://$ip:$port/_nodes/stats/os,process,indices?pretty")
-                echo "$response" | grep "cluster_name" &> /dev/null
-                if [ $? -eq 0 ]; then
+                if echo "$response" | grep -q "cluster_name"; then
                     echo "Successfully fetched node stats."
-                    mkdir -p "$temp_dir"  # Ensure temp directory exists
-                    echo "$response" > "$temp_dir/node_stats.txt" # Save the successful response to "node_stats.txt"
+                    echo "$response" > "$temp_dir/node_stats.txt"
                     return 0
                 else
                     echo "Failed to fetch node stats."
@@ -77,12 +81,12 @@ check_and_enable_flowcoll_logging() {
     else
         echo "Key-value pair $key_value does not exist or is commented out in $file."
         read -p "Would you like to add it? (yes/no): " response
-        if [[ "$response" == "y" ]]; then
+        if [[ $response =~ ^[Yy] ]]; then
             echo "$key_value" | sudo tee -a "$file"
             echo "Added $key_value to $file."
-            
+
             read -p "Would you like to reload the daemon and restart the flowcoll service? (yes/no): " reload_response
-            if [[ "$reload_response" == "y" ]]; then
+            if [[ $reload_response =~ ^[Yy] ]]; then
                 echo "Reloading daemon and restarting flowcoll service..."
                 sudo systemctl daemon-reload
                 sudo systemctl restart flowcoll
@@ -95,8 +99,6 @@ check_and_enable_flowcoll_logging() {
         fi
     fi
 }
-
-
 
 attempt_fetch_saved_objects() {
     local retry_choice
@@ -111,30 +113,20 @@ attempt_fetch_saved_objects() {
     case $share_choice in
         [Yy]* )
             while true; do
-                # Prompt user for inputs with defaults
                 read -p "Enter protocol (http/https) [$default_protocol]: " protocol
                 protocol=${protocol:-$default_protocol}
-
                 read -p "Enter IP address [$default_ip]: " ip
                 ip=${ip:-$default_ip}
-
                 read -p "Enter port [$default_port]: " port
                 port=${port:-$default_port}
-
                 read -p "Enter username [$default_username]: " username
                 username=${username:-$default_username}
-
                 read -s -p "Enter password [$default_password]: " password
                 password=${password:-$default_password}
                 echo
 
-                # Attempt to connect to Kibana
                 response=$(curl -sk -u "$username:$password" "$protocol://$ip:$port/api/status")
-                
-                # Check if the "name" field is present in the response
-                echo "$response" | jq -e '.name' &> /dev/null
-                
-                if [ $? -eq 0 ]; then
+                if echo "$response" | jq -e '.name' &> /dev/null; then
                     echo "Successfully connected to Kibana."
                     KIBANA_URL="$protocol://$ip:$port"
                     USERNAME="$username"
@@ -149,7 +141,6 @@ attempt_fetch_saved_objects() {
                         * ) echo "Exiting without success."; return 1;;
                     esac
                 fi
-
             done
             ;;
         * )
@@ -159,268 +150,183 @@ attempt_fetch_saved_objects() {
     esac
 }
 
-
 backup_saved_objects() {
-# Output file for the exported saved objects
-OUTPUT_FILE="kibana_saved_objects_backup.ndjson"
+    local OUTPUT_FILE="kibana_saved_objects_backup.ndjson"
+    echo "Exporting all saved objects of specific types..."
+    curl -s -u "$USERNAME:$PASSWORD" -X POST "$KIBANA_URL/api/saved_objects/_export" -H "kbn-xsrf: true" -H "Content-Type: application/json" -d '{
+      "type": ["dashboard", "visualization", "search", "index-pattern", "map", "lens"],
+      "includeReferencesDeep": true
+    }' --output "$OUTPUT_FILE"
 
-# Export all saved objects of specific types
-echo "Exporting all saved objects of specific types..."
-curl -s -u "$USERNAME:$PASSWORD" -X POST "$KIBANA_URL/api/saved_objects/_export" -H "kbn-xsrf: true" -H "Content-Type: application/json" -d '{
-  "type": ["dashboard", "visualization", "search", "index-pattern", "map", "lens"],
-  "includeReferencesDeep": true
-}' --output "$OUTPUT_FILE"
-
-
-
-# Check if the export was successful
-if [ $? -eq 0 ]; then
-  echo "All saved objects successfully backed up to $OUTPUT_FILE"
-  mkdir -p "$temp_dir"  # Ensure temp directory exists
-  cp "$OUTPUT_FILE" "$temp_dir/$OUTPUT_FILE"
-  
-else
-  echo "Failed to back up saved objects."
-fi
+    if [ $? -eq 0 ]; then
+        echo "All saved objects successfully backed up to $OUTPUT_FILE"
+        cp "$OUTPUT_FILE" "$temp_dir/$OUTPUT_FILE"
+    else
+        echo "Failed to back up saved objects."
+    fi
 }
 
-
-# Function to get hardware information
 get_system_info() {
-    # Print system information
     echo "=== System Information ==="
     echo "Hostname: $(hostname)"
     echo "Kernel Version: $(uname -r)"
-    echo "Operating System: $(cat /etc/os-release | grep "PRETTY_NAME" | cut -d '"' -f 2)"
+    echo "Operating System: $(grep "PRETTY_NAME" /etc/os-release | cut -d '"' -f 2)"
     echo
 
-    # Print CPU information
     echo "=== CPU Information ==="
     lscpu
     echo
 
-    # Print memory information
     echo "=== Memory Information ==="
     free -h
     echo
 
-    # Print disk information
     echo "=== Disk Information ==="
     df -h
     echo
 
-    # Print PCI devices information
     echo "=== PCI Devices Information ==="
     lspci
     echo
 
-    # Print USB devices information
     echo "=== USB Devices Information ==="
     lsusb
     echo
 
-    # Print network interfaces information
     echo "=== Network Interfaces Information ==="
     ip addr
     echo
 
-    # Print installed software packages
     echo "=== Installed Software Packages ==="
     dpkg -l
     rpm -qa
 
     echo "----------------------------------------------"
     echo "Date and Time: $(date)"
-  
-    echo "----------------------------------------------" 
+
+    echo "----------------------------------------------"
     echo "Operating System Version:"
     uname -a
 
     echo "----------------------------------------------"
     echo "ElastiFlow Flow Collector Version:"
     /usr/share/elastiflow/bin/flowcoll -version 2>/dev/null || echo "ElastiFlow version information not available"
-  
+
     echo "----------------------------------------------"
     echo "ElastiFlow SNMP Collector Version:"
     /usr/share/elastiflow/bin/snmpcoll -version 2>/dev/null || echo "SNMP Collector version information not available"
-     
+
     echo "----------------------------------------------"
     echo "Elasticsearch Version:"
     /usr/share/elasticsearch/bin/elasticsearch -version 2>/dev/null || echo "ElasticSearch version information not available"
-    
+
     echo "----------------------------------------------"
     echo "Kibana Version:"
     /usr/share/kibana/bin/kibana -version 2>/dev/null || echo "Kibana version information not available"
-      
+
     echo "----------------------------------------------"
     echo "Opensearch Version:"
     /usr/share/opensearch/bin/opensearch -version 2>/dev/null || echo "Opensearch version information not available"
-      
+
     echo "----------------------------------------------"
     echo "Open ports:"
     ss -tulpn | grep LISTEN
-    
+
     echo "----------------------------------------------"
     echo "Running Processes:"
     ps -aux
-      
+
     echo "----------------------------------------------"
     echo "Services:"
     systemctl list-unit-files --type=service | grep enabled
-    
+
     echo "----------------------------------------------"
     echo "Network Configuration:"
     ip addr
-     
+
     echo "----------------------------------------------"
     echo "Disk Space Usage:"
     df -h
-     
+
     echo "----------------------------------------------"
     echo "Memory Usage:"
     free -m
     echo "----------------------------------------------"
 }
 
-# Initialize log file
-exec &> >(tee -a "$temp_dir/$log_file") # Capture all output to log file
-
-
-echo "Starting ElastiFlow Support Pack at $(date)"
-
 backup_configs() {
-# Array of paths to copy
-declare -a paths=(
-#dir
-"/etc/elastiflow"
-#dir
-"/etc/sysctl.d"
-#files
-"/etc/sysctl.conf"
+    declare -a paths=(
+        "/etc/elastiflow"
+        "/etc/sysctl.d"
+        "/etc/sysctl.conf"
+        "/etc/kibana/kibana.yml"
+        "/var/log/kibana/kibana.log"
+        "/etc/elasticsearch/elasticsearch.yml"
+        "/etc/elasticsearch/jvm.options.d/heap.options"
+        "/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf"
+        "/var/log/elasticsearch/elasticsearch.log"
+        "/etc/opensearch/opensearch.yml"
+        "/etc/opensearch/jvm.options"
+        "/var/log/opensearch/opensearch.log"
+        "/etc/systemd/system/opensearch.service.d/opensearch.conf"
+        "/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
+        "/usr/lib/sysctl.d/opensearch.conf"
+        "/etc/systemd/system/flowcoll.service.d/flowcoll.conf"
+        "/etc/systemd/system/flowcoll.service"
+        "/var/log/elastiflow/flowcoll/flowcoll.log"
+        "/etc/systemd/system/snmpcoll.service.d/snmpcoll.conf"
+        "/etc/systemd/system/snmpcoll.service"
+        "/var/log/elastiflow/snmpcoll/snmpcoll.log"
+    )
 
-# Kibana config
-"/etc/kibana/kibana.yml"
-"/var/log/kibana/kibana.log"
+    echo "Copying directories and files..."
 
-# Elasticsearch config
-"/etc/elasticsearch/elasticsearch.yml"
-"/etc/elasticsearch/jvm.options.d/heap.options"
-"/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf"
-"/var/log/elasticsearch/elasticsearch.log"
+    for path in "${paths[@]}"; do
+        if [[ ! -e $path ]]; then
+            echo -e "\033[0;31m$path does not exist, skipping...\033[0m"
+            continue
+        fi
 
-# OpenSearch config
-#ubuntu
-"/etc/opensearch/opensearch.yml"
-"/etc/opensearch/jvm.options"
-"/var/log/opensearch/opensearch.log"
-"/etc/systemd/system/opensearch.service.d/opensearch.conf"
-"/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
-
-#debian
-"/usr/lib/sysctl.d/opensearch.conf"
-
-# flowcoll
-"/etc/systemd/system/flowcoll.service.d/flowcoll.conf"
-"/etc/systemd/system/flowcoll.service"
-"/var/log/elastiflow/flowcoll/flowcoll.log"
-
-# snmpcoll
-"/etc/systemd/system/snmpcoll.service.d/snmpcoll.conf"
-"/etc/systemd/system/snmpcoll.service"
-"/var/log/elastiflow/snmpcoll/snmpcoll.log"
-)
-
-# Copy files to temporary directory
-echo "Copying directories and files..."
-
-skip_files() {
-    local file_path="$1"
-    local archive_extensions=("zip" "tar.gz" "rar" "7z" "tar" "gz")
-    local geolite_pattern="(?i).*geolite.*"
-    local mmdb_extension="mmdb"
-
-    # Check if the file is an archive
-    for ext in "${archive_extensions[@]}"; do
-        if [[ "$file_path" == *.$ext ]]; then
-            return 1 # Archive file
+        if [[ -d $path ]]; then
+            find "$path" -type f ! -name "*.mmdb" -exec cp --parents {} "$temp_dir" \; 2>/dev/null && echo -e "\033[0;32mSuccessfully copied $path to $temp_dir\033[0m"
+        else
+            if [[ $path == *.log ]]; then
+                tail -c $(( 1024 * 1024 )) "$path" > "$temp_dir/$(basename "$path")" && echo -e "\033[0;32mSuccessfully copied last 1MB of $path to $temp_dir\033[0m"
+            else
+                cp "$path" "$temp_dir" 2>/dev/null && echo -e "\033[0;32mSuccessfully copied $path to $temp_dir\033[0m"
+            fi
         fi
     done
-
-    # Check if the file contains "Geolite" in any case variation followed by any characters
-    if [[ "$file_path" =~ $geolite_pattern ]]; then
-        return 1 # Contains "Geolite"
-    fi
-
-    # Check if the file has a .mmdb extension
-    if [[ "$file_path" == *.$mmdb ]]; then
-        return 1 # .mmdb file
-    fi
-
-    return 0 # Not an archive, does not contain "Geolite", and is not a .mmdb file
-}
-
-
-# Loop through each path
-for path in "${paths[@]}"; do
-    if [[ ! -e $path ]]; then
-        echo -e "\033[0;31m$path does not exist, skipping...\033[0m"  # Red for errors
-        continue # Skip to the next path if the current one does not exist
-    fi
-
-    if [[ -d $path ]]; then
-      
-        find "$path" -type f ! -name "*.mmdb" -exec cp --parents {} "$temp_dir" \; 2>/dev/null && echo -e "\033[0;32mSuccessfully copied $path to $temp_dir\033[0m"
-    else
-        # It's a file, check if it's a log file by its path
-        if [[ $path == *.log ]]; then
-            # It's a log file, copy only the last 1 MB
-            tail -c $(( 1024 * 1024 )) "$path" > "$temp_dir/$(basename "$path")" && echo -e "\033[0;32mSuccessfully copied last 1MB of $path to $temp_dir\033[0m"
-        else
-            # Not a log file, copy normally
-            cp "$path" "$temp_dir" 2>/dev/null && echo -e "\033[0;32mSuccessfully copied $path to $temp_dir\033[0m"
-        fi
-    fi
-done
 }
 
 wrap_up() {
-
-    # create the archive
     echo "Creating archive..."
     tar -czf $archive_name -C $temp_dir . 2>/dev/null
     echo "Archive created: $archive_name"
-    
-    # Output final details
+
     files_count=$(tar -tzf $archive_name | wc -l)
     echo "Number of files archived: $files_count"
-    
-    # Output the archive size using ls
+
     archive_size=$(ls -l "$archive_name" | awk '{print $5}')
     echo "Archive size: $archive_size bytes"
-    
+
     full_path=$(realpath $archive_name)
     echo -e "\033[32mPlease send this file to ElastiFlow:\n$full_path\033[0m"
-    
-    # Clean up
+
     echo "Cleaning up..."
     rm -rf $temp_dir
-    
+
     echo "Done."
 }
 
+exec &> >(tee -a "$temp_dir/$log_file")
+
+echo "Starting ElastiFlow Support Pack at $(date)"
+
 check_and_enable_flowcoll_logging
-
-# obtain node stats...
 attempt_fetch_node_stats
-
-# back up saved objects
 attempt_fetch_saved_objects
-
-# capture system information
 get_system_info > "$temp_dir/$system_info_file"
-
-# backup configs
 backup_configs
-
-#wrap up
+get_service_logs
 wrap_up
